// Code generated by protoc-gen-go. DO NOT EDIT.
// source: outer.proto

package access

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgType int32

const (
	MsgType_Call MsgType = 0
	MsgType_Push MsgType = 1
)

var MsgType_name = map[int32]string{
	0: "Call",
	1: "Push",
}

var MsgType_value = map[string]int32{
	"Call": 0,
	"Push": 1,
}

func (x MsgType) String() string {
	return proto.EnumName(MsgType_name, int32(x))
}

func (MsgType) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{0}
}

type Device struct {
	Guid                 string   `protobuf:"bytes,1,opt,name=guid,proto3" json:"guid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Device) Reset()         { *m = Device{} }
func (m *Device) String() string { return proto.CompactTextString(m) }
func (*Device) ProtoMessage()    {}
func (*Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{0}
}

func (m *Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Device.Unmarshal(m, b)
}
func (m *Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Device.Marshal(b, m, deterministic)
}
func (m *Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Device.Merge(m, src)
}
func (m *Device) XXX_Size() int {
	return xxx_messageInfo_Device.Size(m)
}
func (m *Device) XXX_DiscardUnknown() {
	xxx_messageInfo_Device.DiscardUnknown(m)
}

var xxx_messageInfo_Device proto.InternalMessageInfo

func (m *Device) GetGuid() string {
	if m != nil {
		return m.Guid
	}
	return ""
}

type Account struct {
	Email                string   `protobuf:"bytes,1,opt,name=email,proto3" json:"email,omitempty"`
	PhoneNum             string   `protobuf:"bytes,2,opt,name=phoneNum,proto3" json:"phoneNum,omitempty"`
	Password             string   `protobuf:"bytes,3,opt,name=password,proto3" json:"password,omitempty"`
	Token                string   `protobuf:"bytes,4,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Account) Reset()         { *m = Account{} }
func (m *Account) String() string { return proto.CompactTextString(m) }
func (*Account) ProtoMessage()    {}
func (*Account) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{1}
}

func (m *Account) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Account.Unmarshal(m, b)
}
func (m *Account) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Account.Marshal(b, m, deterministic)
}
func (m *Account) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Account.Merge(m, src)
}
func (m *Account) XXX_Size() int {
	return xxx_messageInfo_Account.Size(m)
}
func (m *Account) XXX_DiscardUnknown() {
	xxx_messageInfo_Account.DiscardUnknown(m)
}

var xxx_messageInfo_Account proto.InternalMessageInfo

func (m *Account) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *Account) GetPhoneNum() string {
	if m != nil {
		return m.PhoneNum
	}
	return ""
}

func (m *Account) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *Account) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

type ReqHead struct {
	Dev                  *Device  `protobuf:"bytes,1,opt,name=dev,proto3" json:"dev,omitempty"`
	Ver                  string   `protobuf:"bytes,2,opt,name=ver,proto3" json:"ver,omitempty"`
	Account              *Account `protobuf:"bytes,3,opt,name=account,proto3" json:"account,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqHead) Reset()         { *m = ReqHead{} }
func (m *ReqHead) String() string { return proto.CompactTextString(m) }
func (*ReqHead) ProtoMessage()    {}
func (*ReqHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{2}
}

func (m *ReqHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqHead.Unmarshal(m, b)
}
func (m *ReqHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqHead.Marshal(b, m, deterministic)
}
func (m *ReqHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqHead.Merge(m, src)
}
func (m *ReqHead) XXX_Size() int {
	return xxx_messageInfo_ReqHead.Size(m)
}
func (m *ReqHead) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqHead.DiscardUnknown(m)
}

var xxx_messageInfo_ReqHead proto.InternalMessageInfo

func (m *ReqHead) GetDev() *Device {
	if m != nil {
		return m.Dev
	}
	return nil
}

func (m *ReqHead) GetVer() string {
	if m != nil {
		return m.Ver
	}
	return ""
}

func (m *ReqHead) GetAccount() *Account {
	if m != nil {
		return m.Account
	}
	return nil
}

type ReqBody struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Content              []byte   `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ReqBody) Reset()         { *m = ReqBody{} }
func (m *ReqBody) String() string { return proto.CompactTextString(m) }
func (*ReqBody) ProtoMessage()    {}
func (*ReqBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{3}
}

func (m *ReqBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ReqBody.Unmarshal(m, b)
}
func (m *ReqBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ReqBody.Marshal(b, m, deterministic)
}
func (m *ReqBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ReqBody.Merge(m, src)
}
func (m *ReqBody) XXX_Size() int {
	return xxx_messageInfo_ReqBody.Size(m)
}
func (m *ReqBody) XXX_DiscardUnknown() {
	xxx_messageInfo_ReqBody.DiscardUnknown(m)
}

var xxx_messageInfo_ReqBody proto.InternalMessageInfo

func (m *ReqBody) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *ReqBody) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *ReqBody) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

type PkgReqHead struct {
	Seq                  uint64   `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PkgReqHead) Reset()         { *m = PkgReqHead{} }
func (m *PkgReqHead) String() string { return proto.CompactTextString(m) }
func (*PkgReqHead) ProtoMessage()    {}
func (*PkgReqHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{4}
}

func (m *PkgReqHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PkgReqHead.Unmarshal(m, b)
}
func (m *PkgReqHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PkgReqHead.Marshal(b, m, deterministic)
}
func (m *PkgReqHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PkgReqHead.Merge(m, src)
}
func (m *PkgReqHead) XXX_Size() int {
	return xxx_messageInfo_PkgReqHead.Size(m)
}
func (m *PkgReqHead) XXX_DiscardUnknown() {
	xxx_messageInfo_PkgReqHead.DiscardUnknown(m)
}

var xxx_messageInfo_PkgReqHead proto.InternalMessageInfo

func (m *PkgReqHead) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

type PkgReqBody struct {
	Head                 *ReqHead   `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Bodys                []*ReqBody `protobuf:"bytes,2,rep,name=bodys,proto3" json:"bodys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PkgReqBody) Reset()         { *m = PkgReqBody{} }
func (m *PkgReqBody) String() string { return proto.CompactTextString(m) }
func (*PkgReqBody) ProtoMessage()    {}
func (*PkgReqBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{5}
}

func (m *PkgReqBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PkgReqBody.Unmarshal(m, b)
}
func (m *PkgReqBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PkgReqBody.Marshal(b, m, deterministic)
}
func (m *PkgReqBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PkgReqBody.Merge(m, src)
}
func (m *PkgReqBody) XXX_Size() int {
	return xxx_messageInfo_PkgReqBody.Size(m)
}
func (m *PkgReqBody) XXX_DiscardUnknown() {
	xxx_messageInfo_PkgReqBody.DiscardUnknown(m)
}

var xxx_messageInfo_PkgReqBody proto.InternalMessageInfo

func (m *PkgReqBody) GetHead() *ReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *PkgReqBody) GetBodys() []*ReqBody {
	if m != nil {
		return m.Bodys
	}
	return nil
}

type PkgReq struct {
	Head                 *PkgReqHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Body                 *PkgReqBody `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PkgReq) Reset()         { *m = PkgReq{} }
func (m *PkgReq) String() string { return proto.CompactTextString(m) }
func (*PkgReq) ProtoMessage()    {}
func (*PkgReq) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{6}
}

func (m *PkgReq) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PkgReq.Unmarshal(m, b)
}
func (m *PkgReq) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PkgReq.Marshal(b, m, deterministic)
}
func (m *PkgReq) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PkgReq.Merge(m, src)
}
func (m *PkgReq) XXX_Size() int {
	return xxx_messageInfo_PkgReq.Size(m)
}
func (m *PkgReq) XXX_DiscardUnknown() {
	xxx_messageInfo_PkgReq.DiscardUnknown(m)
}

var xxx_messageInfo_PkgReq proto.InternalMessageInfo

func (m *PkgReq) GetHead() *PkgReqHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *PkgReq) GetBody() *PkgReqBody {
	if m != nil {
		return m.Body
	}
	return nil
}

//---------------------------
type RspHead struct {
	Uid                  uint64   `protobuf:"varint,1,opt,name=uid,proto3" json:"uid,omitempty"`
	Token                string   `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	Code                 uint32   `protobuf:"varint,3,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspHead) Reset()         { *m = RspHead{} }
func (m *RspHead) String() string { return proto.CompactTextString(m) }
func (*RspHead) ProtoMessage()    {}
func (*RspHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{7}
}

func (m *RspHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspHead.Unmarshal(m, b)
}
func (m *RspHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspHead.Marshal(b, m, deterministic)
}
func (m *RspHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspHead.Merge(m, src)
}
func (m *RspHead) XXX_Size() int {
	return xxx_messageInfo_RspHead.Size(m)
}
func (m *RspHead) XXX_DiscardUnknown() {
	xxx_messageInfo_RspHead.DiscardUnknown(m)
}

var xxx_messageInfo_RspHead proto.InternalMessageInfo

func (m *RspHead) GetUid() uint64 {
	if m != nil {
		return m.Uid
	}
	return 0
}

func (m *RspHead) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *RspHead) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type RspBody struct {
	Service              string   `protobuf:"bytes,1,opt,name=service,proto3" json:"service,omitempty"`
	Method               string   `protobuf:"bytes,2,opt,name=method,proto3" json:"method,omitempty"`
	Id                   uint32   `protobuf:"varint,3,opt,name=id,proto3" json:"id,omitempty"`
	Content              []byte   `protobuf:"bytes,4,opt,name=content,proto3" json:"content,omitempty"`
	Code                 uint32   `protobuf:"varint,5,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RspBody) Reset()         { *m = RspBody{} }
func (m *RspBody) String() string { return proto.CompactTextString(m) }
func (*RspBody) ProtoMessage()    {}
func (*RspBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{8}
}

func (m *RspBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RspBody.Unmarshal(m, b)
}
func (m *RspBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RspBody.Marshal(b, m, deterministic)
}
func (m *RspBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RspBody.Merge(m, src)
}
func (m *RspBody) XXX_Size() int {
	return xxx_messageInfo_RspBody.Size(m)
}
func (m *RspBody) XXX_DiscardUnknown() {
	xxx_messageInfo_RspBody.DiscardUnknown(m)
}

var xxx_messageInfo_RspBody proto.InternalMessageInfo

func (m *RspBody) GetService() string {
	if m != nil {
		return m.Service
	}
	return ""
}

func (m *RspBody) GetMethod() string {
	if m != nil {
		return m.Method
	}
	return ""
}

func (m *RspBody) GetId() uint32 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *RspBody) GetContent() []byte {
	if m != nil {
		return m.Content
	}
	return nil
}

func (m *RspBody) GetCode() uint32 {
	if m != nil {
		return m.Code
	}
	return 0
}

type PkgRspHead struct {
	Seq                  uint64   `protobuf:"varint,1,opt,name=seq,proto3" json:"seq,omitempty"`
	Type                 MsgType  `protobuf:"varint,2,opt,name=type,proto3,enum=access.MsgType" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PkgRspHead) Reset()         { *m = PkgRspHead{} }
func (m *PkgRspHead) String() string { return proto.CompactTextString(m) }
func (*PkgRspHead) ProtoMessage()    {}
func (*PkgRspHead) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{9}
}

func (m *PkgRspHead) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PkgRspHead.Unmarshal(m, b)
}
func (m *PkgRspHead) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PkgRspHead.Marshal(b, m, deterministic)
}
func (m *PkgRspHead) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PkgRspHead.Merge(m, src)
}
func (m *PkgRspHead) XXX_Size() int {
	return xxx_messageInfo_PkgRspHead.Size(m)
}
func (m *PkgRspHead) XXX_DiscardUnknown() {
	xxx_messageInfo_PkgRspHead.DiscardUnknown(m)
}

var xxx_messageInfo_PkgRspHead proto.InternalMessageInfo

func (m *PkgRspHead) GetSeq() uint64 {
	if m != nil {
		return m.Seq
	}
	return 0
}

func (m *PkgRspHead) GetType() MsgType {
	if m != nil {
		return m.Type
	}
	return MsgType_Call
}

type PkgRspBody struct {
	Head                 *RspHead   `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Bodys                []*RspBody `protobuf:"bytes,2,rep,name=bodys,proto3" json:"bodys,omitempty"`
	XXX_NoUnkeyedLiteral struct{}   `json:"-"`
	XXX_unrecognized     []byte     `json:"-"`
	XXX_sizecache        int32      `json:"-"`
}

func (m *PkgRspBody) Reset()         { *m = PkgRspBody{} }
func (m *PkgRspBody) String() string { return proto.CompactTextString(m) }
func (*PkgRspBody) ProtoMessage()    {}
func (*PkgRspBody) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{10}
}

func (m *PkgRspBody) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PkgRspBody.Unmarshal(m, b)
}
func (m *PkgRspBody) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PkgRspBody.Marshal(b, m, deterministic)
}
func (m *PkgRspBody) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PkgRspBody.Merge(m, src)
}
func (m *PkgRspBody) XXX_Size() int {
	return xxx_messageInfo_PkgRspBody.Size(m)
}
func (m *PkgRspBody) XXX_DiscardUnknown() {
	xxx_messageInfo_PkgRspBody.DiscardUnknown(m)
}

var xxx_messageInfo_PkgRspBody proto.InternalMessageInfo

func (m *PkgRspBody) GetHead() *RspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *PkgRspBody) GetBodys() []*RspBody {
	if m != nil {
		return m.Bodys
	}
	return nil
}

type PkgRsp struct {
	Head                 *PkgRspHead `protobuf:"bytes,1,opt,name=head,proto3" json:"head,omitempty"`
	Body                 *PkgRspBody `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PkgRsp) Reset()         { *m = PkgRsp{} }
func (m *PkgRsp) String() string { return proto.CompactTextString(m) }
func (*PkgRsp) ProtoMessage()    {}
func (*PkgRsp) Descriptor() ([]byte, []int) {
	return fileDescriptor_c96bfb384e37eb24, []int{11}
}

func (m *PkgRsp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PkgRsp.Unmarshal(m, b)
}
func (m *PkgRsp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PkgRsp.Marshal(b, m, deterministic)
}
func (m *PkgRsp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PkgRsp.Merge(m, src)
}
func (m *PkgRsp) XXX_Size() int {
	return xxx_messageInfo_PkgRsp.Size(m)
}
func (m *PkgRsp) XXX_DiscardUnknown() {
	xxx_messageInfo_PkgRsp.DiscardUnknown(m)
}

var xxx_messageInfo_PkgRsp proto.InternalMessageInfo

func (m *PkgRsp) GetHead() *PkgRspHead {
	if m != nil {
		return m.Head
	}
	return nil
}

func (m *PkgRsp) GetBody() *PkgRspBody {
	if m != nil {
		return m.Body
	}
	return nil
}

func init() {
	proto.RegisterEnum("access.MsgType", MsgType_name, MsgType_value)
	proto.RegisterType((*Device)(nil), "access.Device")
	proto.RegisterType((*Account)(nil), "access.Account")
	proto.RegisterType((*ReqHead)(nil), "access.ReqHead")
	proto.RegisterType((*ReqBody)(nil), "access.ReqBody")
	proto.RegisterType((*PkgReqHead)(nil), "access.PkgReqHead")
	proto.RegisterType((*PkgReqBody)(nil), "access.PkgReqBody")
	proto.RegisterType((*PkgReq)(nil), "access.PkgReq")
	proto.RegisterType((*RspHead)(nil), "access.RspHead")
	proto.RegisterType((*RspBody)(nil), "access.RspBody")
	proto.RegisterType((*PkgRspHead)(nil), "access.PkgRspHead")
	proto.RegisterType((*PkgRspBody)(nil), "access.PkgRspBody")
	proto.RegisterType((*PkgRsp)(nil), "access.PkgRsp")
}

func init() { proto.RegisterFile("outer.proto", fileDescriptor_c96bfb384e37eb24) }

var fileDescriptor_c96bfb384e37eb24 = []byte{
	// 451 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x9c, 0x54, 0x51, 0x8b, 0xd3, 0x40,
	0x10, 0xb6, 0x49, 0x9a, 0x9c, 0x53, 0xad, 0x65, 0x11, 0x09, 0xa2, 0x52, 0x56, 0x3c, 0xd4, 0x87,
	0x3e, 0x9c, 0xbf, 0x40, 0x4f, 0xc1, 0x17, 0xe5, 0x58, 0x14, 0xee, 0x35, 0x97, 0x1d, 0x9a, 0x70,
	0x6d, 0x37, 0x97, 0x4d, 0x2a, 0xf9, 0xf7, 0xb2, 0xb3, 0xb3, 0xed, 0xe5, 0xc4, 0x13, 0x7c, 0x9b,
	0xe1, 0xdb, 0xf9, 0xbe, 0xf9, 0xe6, 0x0b, 0x81, 0x99, 0xe9, 0x3b, 0x6c, 0x57, 0x4d, 0x6b, 0x3a,
	0x23, 0xd2, 0xa2, 0x2c, 0xd1, 0x5a, 0xf9, 0x02, 0xd2, 0xcf, 0xb8, 0xaf, 0x4b, 0x14, 0x02, 0x92,
	0x75, 0x5f, 0xeb, 0x7c, 0xb2, 0x9c, 0xbc, 0x7d, 0xa8, 0xa8, 0x96, 0x5b, 0xc8, 0x3e, 0x96, 0xa5,
	0xe9, 0x77, 0x9d, 0x78, 0x0a, 0x53, 0xdc, 0x16, 0xf5, 0x86, 0x71, 0xdf, 0x88, 0xe7, 0x70, 0xd2,
	0x54, 0x66, 0x87, 0xdf, 0xfb, 0x6d, 0x1e, 0x11, 0x70, 0xe8, 0x09, 0x2b, 0xac, 0xfd, 0x65, 0x5a,
	0x9d, 0xc7, 0x8c, 0x71, 0xef, 0xd8, 0x3a, 0x73, 0x8d, 0xbb, 0x3c, 0xf1, 0x6c, 0xd4, 0xc8, 0x0a,
	0x32, 0x85, 0x37, 0x5f, 0xb1, 0xd0, 0x62, 0x09, 0xb1, 0xc6, 0x3d, 0x89, 0xcd, 0xce, 0xe6, 0x2b,
	0xbf, 0xed, 0xca, 0xaf, 0xaa, 0x1c, 0x24, 0x16, 0x10, 0xef, 0xb1, 0x65, 0x55, 0x57, 0x8a, 0x77,
	0x90, 0x15, 0x7e, 0x5b, 0xd2, 0x9b, 0x9d, 0x3d, 0x09, 0x73, 0x6c, 0x42, 0x05, 0x5c, 0xfe, 0x24,
	0xa5, 0x4f, 0x46, 0x0f, 0x22, 0x87, 0xcc, 0x62, 0xeb, 0x78, 0xd9, 0x5a, 0x68, 0xc5, 0x33, 0x48,
	0xb7, 0xd8, 0x55, 0x46, 0xb3, 0x08, 0x77, 0x6e, 0xa2, 0x34, 0xbb, 0x0e, 0x59, 0xe7, 0x91, 0x0a,
	0xad, 0x7c, 0x05, 0x70, 0x71, 0xbd, 0x0e, 0x1e, 0x16, 0x10, 0x5b, 0xbc, 0x21, 0xd6, 0x44, 0xb9,
	0x52, 0x5e, 0x06, 0x9c, 0x94, 0x5f, 0x43, 0x52, 0x61, 0xa1, 0xd9, 0xe4, 0x61, 0x59, 0x1e, 0x57,
	0x04, 0x8a, 0x37, 0x30, 0xbd, 0x32, 0x7a, 0xb0, 0x79, 0xb4, 0x8c, 0xef, 0xbc, 0x72, 0x24, 0xca,
	0xa3, 0xf2, 0x12, 0x52, 0xcf, 0x2c, 0x4e, 0x47, 0xac, 0x22, 0xbc, 0x3f, 0xee, 0xc5, 0xc4, 0xa7,
	0x90, 0xb8, 0x51, 0xf2, 0xf6, 0xc7, 0x3b, 0xa2, 0x26, 0x5c, 0x7e, 0x81, 0x4c, 0xd9, 0x26, 0x18,
	0x0a, 0x5f, 0x48, 0xa2, 0x5c, 0x79, 0xcc, 0x31, 0xba, 0x95, 0xa3, 0xfb, 0x94, 0x4a, 0xa3, 0x91,
	0xae, 0xf3, 0x58, 0x51, 0x2d, 0x07, 0xa2, 0xf9, 0xcf, 0x8b, 0xcf, 0x21, 0xaa, 0x35, 0xd3, 0x45,
	0xf5, 0x28, 0x81, 0x64, 0x94, 0xc0, 0x41, 0x7a, 0x7a, 0x4b, 0xfa, 0xdc, 0x5f, 0xfd, 0x68, 0x62,
	0x9c, 0x8a, 0xcb, 0xa1, 0x1b, 0x1a, 0x24, 0xcd, 0xf9, 0xf1, 0xc2, 0xdf, 0xec, 0xfa, 0xc7, 0xd0,
	0xa0, 0x22, 0x30, 0x44, 0xc7, 0x16, 0xfe, 0x16, 0x9d, 0xd7, 0xf8, 0x57, 0x74, 0x9e, 0xe4, 0x4e,
	0x74, 0xb6, 0xb9, 0x2f, 0xba, 0x11, 0xf1, 0x3d, 0xd1, 0x31, 0x35, 0xe1, 0xef, 0x5f, 0x42, 0xc6,
	0x26, 0xc4, 0x09, 0x24, 0xe7, 0xc5, 0x66, 0xb3, 0x78, 0xe0, 0xaa, 0x8b, 0xde, 0x56, 0x8b, 0xc9,
	0x55, 0x4a, 0xbf, 0x82, 0x0f, 0xbf, 0x03, 0x00, 0x00, 0xff, 0xff, 0xe2, 0xf7, 0x34, 0x70, 0x19,
	0x04, 0x00, 0x00,
}
